- zillow_id
- home_type
- home_detail_link
- graph_data_link
- map_this_home_link
- latitude
- latitude
- coordinates (as GEOS point)
- tax_year
- tax_value
- year_built
- property_size
- home_size
- bathrooms
- bedrooms
- last_sold_date
- last_sold_price_currency
- last_sold_price
- zestimate_amount
- zestimate_last_updated
- zestimate_value_change
- zestimate_valuation_range_high
- zestimate_valuationRange_low
- zestimate_percentile

In [40]:
from pyzillow.pyzillow import ZillowWrapper, GetDeepSearchResults
import pandas as pd
import csv
import pandas_profiling as pp
import matplotlib.pyplot as plt
import numpy as np
import requests
import itertools
from tqdm import tqdm

api_key = "X1-ZWz1fkoowi9erv_4dboj"
df = pd.read_csv('/Users/PatrickChen/Desktop/dsi-atx-1-projects-pchen2890/CAPSTONE/airbnb_data.csv',encoding="utf8")

In [41]:
df.head()

,Unnamed: 0,dateAdded,lat,long,propertyType,prices,house_num,street_name,zipcodes
0,0,2015-10-28,30.261685,-97.707917,House,107.0,2816,Prado Street,78702
1,3,2015-11-05,30.439717,-97.753116,House,59.0,6508,McNeil Drive,78729
2,5,2015-10-21,30.272969,-97.805890,House,100.0,3409,Rosefinch Trail,78746
3,7,2016-04-08,30.242879,-97.896568,House,65.0,8500,Red Willow Drive,78736
4,10,2016-08-05,30.369334,-97.651486,House,44.0,2121,Tin Can Drive,78754

In [42]:
df.propertyType = df.propertyType.apply(lambda x: str(x))
df.house_num = df.house_num.apply(lambda x: str(x))
df.street_name = df.street_name.apply(lambda x: x.encode('utf8'))

In [43]:
df["address"] = df.house_num+" "+df.street_name

In [44]:
data = df[["propertyType","prices","zipcodes","address"]]

In [45]:
data.address = data.address.str.replace(" ","+")

In [46]:
data.head()

  propertyType  prices  zipcodes                address
0        House   107.0     78702      2816+Prado+Street
1        House    59.0     78729      6508+McNeil+Drive
2        House   100.0     78746   3409+Rosefinch+Trail
3        House    65.0     78736  8500+Red+Willow+Drive
4        House    44.0     78754     2121+Tin+Can+Drive

In [47]:
home_type = []
tax_year = []
tax_value = []
year_built = []
property_size = []
home_size = []
bathrooms = []
bedrooms = []
zestimate_amount = []

for a,z in tqdm(itertools.izip_longest(data.address,data.zipcodes)):
    url = "http://www.zillow.com/webservice/GetDeepSearchResults.htm?zws-id="+api_key+"&address="+a+"&citystatezip="+str(z)
    response = requests.get(url)
    if "no exact match found" in str(response.text):
        home_type.append("none")
        tax_year.append("none")
        tax_value.append("none")
        year_built.append("none")
        property_size.append("none")
        home_size.append("none")
        bathrooms.append("none")
        bedrooms.append("none")
        zestimate_amount.append("none")
    else:
        zillow_data = ZillowWrapper(api_key)
        deep_search_response = zillow_data.get_deep_search_results(a, z)
        result = GetDeepSearchResults(deep_search_response)
        
        home_type.append(result.home_type)
        tax_year.append(result.tax_year)
        tax_value.append(result.tax_value)
        year_built.append(result.year_built)
        property_size.append(result.property_size)
        home_size.append(result.home_size)
        bathrooms.append(result.bathrooms)
        bedrooms.append(result.bedrooms)
        zestimate_amount.append(result.zestimate_amount)

716it [04:15,  2.81it/s]

In [48]:
data["home_type"] = home_type
data["tax_year"] = tax_year
data["tax_value"] = tax_value
data["year_built"] = year_built
data["property_size"] = property_size
data["home_size"] = home_size
data["bathrooms"] = bathrooms
data["bedrooms"] = bedrooms
data["zestimate_amount"] = zestimate_amount

/Users/PatrickChen/anaconda/envs/dsienv/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/PatrickChen/anaconda/envs/dsienv/lib/python2.7/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/Users/PatrickChen/anaconda/envs/dsienv/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/Users/PatrickChen/anaconda/envs/dsienv/lib/python2.7/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/PatrickChen/anaconda/envs/dsienv/lib/python2.7/site-packages/ipykernel/__main__.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [49]:
data.head()

,propertyType,prices,zipcodes,address,home_type,tax_year,tax_value,year_built,property_size,home_size,bathrooms,bedrooms,zestimate_amount
0,House,107.0,78702,2816+Prado+Street,SingleFamily,2015,192439.0,1961,6294,730,1.0,2,281162
1,House,59.0,78729,6508+McNeil+Drive,none,none,none,none,none,none,none,none,none
2,House,100.0,78746,3409+Rosefinch+Trail,SingleFamily,2015,491696.0,1981,9409,1991,2.0,None,640646
3,House,65.0,78736,8500+Red+Willow+Drive,SingleFamily,None,None,2008,13068,3026,3.0,4,399599
4,House,44.0,78754,2121+Tin+Can+Drive,SingleFamily,2015,187606.0,2010,5872,1764,3.0,3,216260

In [68]:
data = data[data.zestimate_amount!="none"]
data = data.drop("address",axis=1)

In [82]:
data.tax_year = data.tax_year.astype(float)
data.tax_value = data.tax_value.astype(float)
data.year_built = data.year_built.astype(float)
data.property_size = data.property_size.astype(float)
data.home_size = data.home_size.astype(float)
data.bathrooms = data.bathrooms.astype(float)
data.bedrooms = data.bedrooms.astype(float)
data.zestimate_amount = data.zestimate_amount.astype(float)

In [83]:
data.dtypes

propertyType         object
prices              float64
zipcodes              int64
home_type            object
tax_year            float64
tax_value           float64
year_built          float64
property_size       float64
home_size           float64
bathrooms           float64
bedrooms            float64
zestimate_amount    float64
dtype: object

In [84]:
data.corr()

,prices,zipcodes,tax_year,tax_value,year_built,property_size,home_size,bathrooms,bedrooms,zestimate_amount
prices,1.000000,-0.007166,-0.026618,0.034296,0.000336,-0.006788,-0.003811,0.034006,-0.003702,0.087262
zipcodes,-0.007166,1.000000,0.072767,-0.015133,0.237655,-0.046606,0.009895,0.165609,0.176229,-0.060120
tax_year,-0.026618,0.072767,1.000000,0.004177,-0.028408,0.005254,0.008968,0.020106,0.004911,-0.039271
tax_value,0.034296,-0.015133,0.004177,1.000000,0.058843,-0.000892,0.743400,0.080704,-0.085740,0.247121
year_built,0.000336,0.237655,-0.028408,0.058843,1.000000,0.074285,0.087730,0.360356,0.216222,0.049982
property_size,-0.006788,-0.046606,0.005254,-0.000892,0.074285,1.000000,-0.006330,-0.017887,-0.062097,0.034908
home_size,-0.003811,0.009895,0.008968,0.743400,0.087730,-0.006330,1.000000,0.652582,0.480650,0.227400
bathrooms,0.034006,0.165609,0.020106,0.080704,0.360356,-0.017887,0.652582,1.000000,0.565920,0.546390
bedrooms,-0.003702,0.176229,0.004911,-0.085740,0.216222,-0.062097,0.480650,0.565920,1.000000,0.338496
zestimate_amount,0.087262,-0.060120,-0.039271,0.247121,0.049982,0.034908,0.227400,0.546390,0.338496,1.000000

In [ ]:
data.to_csv('/Users/PatrickChen/Desktop/dsi-atx-1-projects-pchen2890/CAPSTONE/zillow_AnB_data.csv')